default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: noobtwit_development

test:
  <<: *default
  database: noobtwit_test

production:
  <<: *default
  database: noobtwit_production
#  username: noobtwit
#  password: <%= ENV['NOOBTWIT_DATABASE_PASSWORD'] %>
